module BMValidation

using JGCM, Random

const RD = 287.04
const RV = 461.5
const EPSILON = RD / RV
const TAU = 7200.0
const RH = 0.8

atmosphere(nd; virtual = true) = Atmo_Data(
    "bm_validation", 1, 1, nd, false, false, false, virtual, [0.0]; radius = 6.371e6,
)

function fixture(name)
    path = joinpath(@__DIR__, "..", "fixtures", "betts_miller_$(name)_column.tsv")
    rows = filter(line -> !isempty(strip(line)) && !startswith(strip(line), "#"), readlines(path))
    data = permutedims(reduce(hcat, [parse.(Float64, split(line)) for line in rows]))
    return (;
        name = "fixture_" * name, kind = :fixture, reference = true,
        p_full = data[:, 1], p_half = vcat(data[:, 2], data[end, 3]),
        temperature = data[:, 4], humidity = data[:, 5],
    )
end

"""Fixed-seed input columns; expected answers are never generated by BM."""
function ensemble(; seed = 20261005, count = 96, nd = 30)
    rng = MersenneTwister(seed)
    cases = [fixture(name) for name in ("deep", "shallow", "virtual")]
    for index = 1:count
        grid = mod1(index, 3)
        ps = 90000.0 + 15000.0 * rand(rng)
        eta = collect(range(0.0, 1.0; length = nd + 1))
        ph = grid == 1 ? 1000.0 .+ (ps - 1000.0) .* eta :
             grid == 2 ? 1000.0 .+ (ps - 1000.0) .* eta.^1.5 :
             exp.(log(1000.0) .+ log(ps / 1000.0) .* eta)
        pf = 0.5 .* (ph[1:end-1] + ph[2:end])
        kind = (:stable, :unstable, :inverted, :dry)[mod1(index, 4)]
        t0 = 285.0 + 25.0 * rand(rng)
        alpha = kind == :stable ? 0.03 + 0.05 * rand(rng) : 0.14 + 0.13 * rand(rng)
        temperature = max.(200.0, t0 .* (pf ./ pf[end]).^alpha)
        if kind == :inverted
            temperature .+= 10.0 .* exp.(-((pf ./ pf[end] .- 0.8) ./ 0.045).^2)
        end
        rh_upper = 0.05 + 0.92 * rand(rng)
        rh_surface = (0.3, 0.6, 0.8, 0.95, 1.0)[mod1(index, 5)]
        humidity = rh_upper .* Saturation_Specific_Humidity.(temperature, pf, EPSILON)
        humidity[end] = rh_surface * Saturation_Specific_Humidity(temperature[end], pf[end], EPSILON)
        if kind == :dry
            humidity .= isodd(index ÷ 4) ? 0.0 : 1.0e-12
        end
        push!(cases, (;
            name = "seed_$(index)_$(kind)_grid$(grid)", kind,
            reference = kind != :dry, p_full = pf, p_half = ph, temperature, humidity,
        ))
    end
    # Moist profiles spanning small/large thermal integrals deliberately
    # exercise both deep branches, rather than relying on a random sample.
    ph = collect(range(1000.0, 100000.0; length = nd + 1))
    pf = 0.5 .* (ph[1:end-1] + ph[2:end])
    for alpha in (0.10, 0.12, 0.14, 0.17), rh_surface in (0.8, 0.95, 1.0)
        temperature = max.(200.0, 300.0 .* (pf ./ pf[end]).^alpha)
        humidity = 0.99 .* Saturation_Specific_Humidity.(temperature, pf, EPSILON)
        humidity[end] = rh_surface * Saturation_Specific_Humidity(300.0, pf[end], EPSILON)
        push!(cases, (;
            name = "moist_profile_a$(alpha)_rh$(rh_surface)", kind = :moist, reference = true,
            p_full = copy(pf), p_half = copy(ph), temperature, humidity,
        ))
    end
    # Edge columns use physical invariants: Isca's original code clamps an
    # out-of-domain LCL and leaves LZB=0 for buoyancy reaching the model top.
    for top_pressure in (0.0, 30000.0)
        ph = collect(range(top_pressure, 100000.0; length = nd + 1))
        pf = 0.5 .* (ph[1:end-1] + ph[2:end])
        temperature = 300.0 .* (pf ./ pf[end]).^(2 / 7)
        humidity = fill(top_pressure == 0 ? 0.0 : 1.0e-12, nd)
        push!(cases, (;
            name = "dry_neutral_top$(Int(top_pressure))", kind = :edge, reference = false,
            p_full = pf, p_half = ph, temperature, humidity,
        ))
    end
    ph = collect(range(30000.0, 100000.0; length = nd + 1))
    pf = 0.5 .* (ph[1:end-1] + ph[2:end])
    temperature = fill(200.0, nd)
    temperature[end] = 300.0
    humidity = 0.1 .* Saturation_Specific_Humidity.(temperature, pf, EPSILON)
    humidity[end] = Saturation_Specific_Humidity(300.0, pf[end], EPSILON)
    push!(cases, (;
        name = "buoyant_to_finite_top", kind = :edge, reference = false,
        p_full = pf, p_half = ph, temperature, humidity,
    ))
    return cases
end

function grid_fields(cases)
    nd = length(first(cases).p_full)
    # Use several latitude rows to exercise parallel work buffers, with unlike
    # columns on each row. Repeat the first inputs to pad the grid if needed.
    nlat = 4
    nlon = cld(length(cases), nlat)
    fields = ntuple(i -> zeros(nlon, nlat, i == 4 ? nd + 1 : nd), 4)
    for j = 1:nlat, i = 1:nlon
        column = cases[mod1(i + (j - 1) * nlon, length(cases))]
        for (field, key) in zip(fields, (:temperature, :humidity, :p_full, :p_half))
            field[i, j, :] .= getproperty(column, key)
        end
    end
    return fields
end

function grid_outputs(cases; mode = :isca, virtual = true)
    temperature, humidity, pf, ph = grid_fields(cases)
    nlon, nlat, nd = size(temperature)
    state = Betts_Miller_State(nd; energy_correction = mode)
    atmo = atmosphere(nd; virtual)
    dt, dq, rain = zeros(nlon, nlat, nd), zeros(nlon, nlat, nd), zeros(nlon, nlat, 1)
    Betts_Miller!(state, atmo, temperature, humidity, pf, ph, dt, dq, rain)
    return (; dt, dq, rain)
end

end
